### ISSUE TITLE
AttributeError: 'ADXL345Probe' object has no attribute 'probing_move'

### ISSUE THREAD

**Issue by Samuel-0-0** [jniebuhr/adxl345-probe#8]
Internal error on command:"QUAD_GANTRY_LEVEL"
Internal Error on WebRequest: gcode/script
Traceback (most recent call last):
  File "/home/samuel/klipper/klippy/webhooks.py", line 256, in _process_request
    func(web_request)
  File "/home/samuel/klipper/klippy/webhooks.py", line 436, in _handle_script
    self.gcode.run_script(web_request.get_str('script'))
  File "/home/samuel/klipper/klippy/gcode.py", line 229, in run_script
    self._process_commands(script.split('\n'), need_ack=False)
  File "/home/samuel/klipper/klippy/gcode.py", line 211, in _process_commands
    handler(gcmd)
  File "/home/samuel/klipper/klippy/gcode.py", line 137, in <lambda>
    func = lambda params: origfunc(self._get_extended_params(params))
  File "/home/samuel/klipper/klippy/extras/quad_gantry_level.py", line 53, in cmd_QUAD_GANTRY_LEVEL
    self.probe_helper.start_probe(gcmd)
  File "/home/samuel/klipper/klippy/extras/probe.py", line 444, in start_probe
    pos = probe.run_probe(gcmd)
  File "/home/samuel/klipper/klippy/extras/probe.py", line 174, in run_probe
    pos = self._probe(speed)
  File "/home/samuel/klipper/klippy/extras/probe.py", line 123, in _probe
    epos = self.mcu_probe.probing_move(pos, speed)
AttributeError: 'ADXL345Probe' object has no attribute 'probing_move'

**Comment by MidweekMouse505** [comment]
replace the contents of the adxl345_probe.py file with the contents of this updated config: 
[adxl345_probe.txt](https://github.com/jniebuhr/adxl345-probe/files/15419125/adxl345_probe.txt)

**Comment by jniebuhr** [comment]
I pushed @MidweekMouse505 changes to master, you should be able to just update
